[tool.commitizen]
name = "cz_customize"
version = "1.0.0.dev0"
tag_format = "schedule@${version}"
bump_message = "bump(schedule): version $current_version → $new_version"
# Avoid noise from other tags
ignored_tag_formats = ["*@${version}"]
version_files = ["pyproject.toml:version"]
# We hook into commitizen's pre-bump to refresh the workspace lockfile
pre_bump_hooks = ["uv lock", "git add :/uv.lock"]

[tool.commitizen.customize]
changelog_pattern = "^(feat|fix)\\(schedule\\)(!)?:"
