# Generated by Django 5.2.15 on 2026-07-01 13:45

import uuid

import django.core.serializers.json
import django.db.models.deletion
import nautobot.core.models.fields
import nautobot.extras.models.mixins
from django.conf import settings
from django.db import migrations, models

import nautobot_calendars.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("extras", "0142_remove_scheduledjob_approval_required"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "_custom_field_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "tags",
                    nautobot.core.models.fields.TagsField(
                        through="extras.TaggedItem",
                        to="extras.Tag",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                nautobot.extras.models.mixins.DataComplianceModelMixin,
                nautobot.extras.models.mixins.DynamicGroupMixin,
                nautobot.extras.models.mixins.NotesMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="Calendar",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "_custom_field_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "tags",
                    nautobot.core.models.fields.TagsField(
                        through="extras.TaggedItem",
                        to="extras.Tag",
                    ),
                ),
                (
                    "calendar_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendars",
                        to="nautobot_calendars.calendartype",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                nautobot.extras.models.mixins.DataComplianceModelMixin,
                nautobot.extras.models.mixins.DynamicGroupMixin,
                nautobot.extras.models.mixins.NotesMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="RecurrenceRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "_custom_field_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("freq", models.PositiveIntegerField()),
                ("interval", models.PositiveIntegerField(default=1)),
                ("count", models.PositiveIntegerField(blank=True, null=True)),
                ("until", models.DateTimeField(blank=True, null=True)),
                (
                    "bysecond",
                    models.JSONField(
                        blank=True,
                        default=tuple,
                        validators=[
                            nautobot_calendars.validators.JSONSchemaValidator(
                                schema={
                                    "items": {
                                        "maximum": 60,
                                        "minimum": 0,
                                        "type": "integer",
                                    },
                                    "type": "array",
                                },
                            ),
                        ],
                    ),
                ),
                (
                    "byminute",
                    models.JSONField(
                        blank=True,
                        default=list,
                        validators=[
                            nautobot_calendars.validators.JSONSchemaValidator(
                                schema={
                                    "items": {
                                        "maximum": 59,
                                        "minimum": 0,
                                        "type": "integer",
                                    },
                                    "type": "array",
                                },
                            ),
                        ],
                    ),
                ),
                (
                    "byhour",
                    models.JSONField(
                        blank=True,
                        default=list,
                        validators=[
                            nautobot_calendars.validators.JSONSchemaValidator(
                                schema={
                                    "items": {
                                        "maximum": 23,
                                        "minimum": 0,
                                        "type": "integer",
                                    },
                                    "type": "array",
                                },
                            ),
                        ],
                    ),
                ),
                (
                    "byday",
                    models.JSONField(
                        blank=True,
                        default=list,
                        validators=[
                            nautobot_calendars.validators.JSONSchemaValidator(
                                schema={
                                    "items": {
                                        "pattern": "^([+-]?[0-4]?[0-9]|5[0-3])?(MO|TU|WE|TH|FR|SA|SU)$",
                                        "type": "string",
                                    },
                                    "type": "array",
                                },
                            ),
                        ],
                    ),
                ),
                (
                    "bymonthday",
                    models.JSONField(
                        blank=True,
                        default=list,
                        validators=[
                            nautobot_calendars.validators.JSONSchemaValidator(
                                schema={
                                    "items": {
                                        "anyOf": [
                                            {
                                                "maximum": -1,
                                                "minimum": -31,
                                                "type": "integer",
                                            },
                                            {
                                                "maximum": 31,
                                                "minimum": 1,
                                                "type": "integer",
                                            },
                                        ],
                                    },
                                    "type": "array",
                                },
                            ),
                        ],
                    ),
                ),
                (
                    "byyearday",
                    models.JSONField(
                        blank=True,
                        default=list,
                        validators=[
                            nautobot_calendars.validators.JSONSchemaValidator(
                                schema={
                                    "items": {
                                        "anyOf": [
                                            {
                                                "maximum": -1,
                                                "minimum": -366,
                                                "type": "integer",
                                            },
                                            {
                                                "maximum": 366,
                                                "minimum": 1,
                                                "type": "integer",
                                            },
                                        ],
                                    },
                                    "type": "array",
                                },
                            ),
                        ],
                    ),
                ),
                (
                    "byweekno",
                    models.JSONField(
                        blank=True,
                        default=list,
                        validators=[
                            nautobot_calendars.validators.JSONSchemaValidator(
                                schema={
                                    "items": {
                                        "anyOf": [
                                            {
                                                "maximum": -1,
                                                "minimum": -53,
                                                "type": "integer",
                                            },
                                            {
                                                "maximum": 53,
                                                "minimum": 1,
                                                "type": "integer",
                                            },
                                        ],
                                    },
                                    "type": "array",
                                },
                            ),
                        ],
                    ),
                ),
                (
                    "bymonth",
                    models.JSONField(
                        blank=True,
                        default=list,
                        validators=[
                            nautobot_calendars.validators.JSONSchemaValidator(
                                schema={
                                    "items": {
                                        "maximum": 12,
                                        "minimum": 1,
                                        "type": "integer",
                                    },
                                    "type": "array",
                                },
                            ),
                        ],
                    ),
                ),
                (
                    "bysetpos",
                    models.JSONField(
                        blank=True,
                        default=list,
                        validators=[
                            nautobot_calendars.validators.JSONSchemaValidator(
                                schema={
                                    "items": {
                                        "anyOf": [
                                            {
                                                "maximum": -1,
                                                "minimum": -366,
                                                "type": "integer",
                                            },
                                            {
                                                "maximum": 366,
                                                "minimum": 1,
                                                "type": "integer",
                                            },
                                        ],
                                    },
                                    "type": "array",
                                },
                            ),
                        ],
                    ),
                ),
                ("wkst", models.PositiveIntegerField(default=0)),
                (
                    "tags",
                    nautobot.core.models.fields.TagsField(
                        through="extras.TaggedItem",
                        to="extras.Tag",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                nautobot.extras.models.mixins.DataComplianceModelMixin,
                nautobot.extras.models.mixins.DynamicGroupMixin,
                nautobot.extras.models.mixins.NotesMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "_custom_field_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("dtstart", models.DateTimeField()),
                ("dtend", models.DateTimeField()),
                ("priority", models.PositiveIntegerField(default=1)),
                (
                    "exdates",
                    models.JSONField(
                        blank=True,
                        default=list,
                        validators=[
                            nautobot_calendars.validators.JSONSchemaValidator(
                                schema={
                                    "items": {
                                        "pattern": "^\\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12]\\d|3[01]) ([01]\\d|2[0-3]):[0-5]\\d:[0-5]\\d$",
                                    },
                                    "type": "array",
                                },
                            ),
                        ],
                    ),
                ),
                (
                    "rdates",
                    models.JSONField(
                        blank=True,
                        default=list,
                        validators=[
                            nautobot_calendars.validators.JSONSchemaValidator(
                                schema={
                                    "items": {
                                        "pattern": "^\\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12]\\d|3[01]) ([01]\\d|2[0-3]):[0-5]\\d:[0-5]\\d$",
                                    },
                                    "type": "array",
                                },
                            ),
                        ],
                    ),
                ),
                (
                    "calendar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="nautobot_calendars.calendar",
                    ),
                ),
                (
                    "organizer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tags",
                    nautobot.core.models.fields.TagsField(
                        through="extras.TaggedItem",
                        to="extras.Tag",
                    ),
                ),
                (
                    "recurrence_rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="nautobot_calendars.recurrencerule",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                nautobot.extras.models.mixins.DataComplianceModelMixin,
                nautobot.extras.models.mixins.DynamicGroupMixin,
                nautobot.extras.models.mixins.NotesMixin,
                models.Model,
            ),
        ),
    ]
