---
name: GH Pages Cleanup
description: Delete GitHub Pages deployments

on:
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest

    permissions: write-all

    steps:
      - uses: strumwolf/delete-deployment-environment@035f6d27c8b8951729f4d71b2d3d6a7975139476  # v4.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: github-pages
          onlyRemoveDeployments: true
